%define rpm_url https://packages.microsoft.com/opensuse/15/prod/Packages/d/dotnet-apphost-pack-9.0-9.0.3-1.x86_64.rpm
# rpmrebuild autogenerated specfile

%define defaultbuildroot /
AutoProv: no
%undefine __find_provides
AutoReq: no
%undefine __find_requires
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0
#dummy
#dummy
#BUILDHOST:    abd8d6351f20
#BUILDTIME:    Tue Feb 11 23:29:25 2025
#SOURCERPM:    dotnet-apphost-pack-9.0-9.0.3-1.src.rpm

#RPMVERSION:   4.18.2



#OS:           linux
#SIZE:           13227539
#ARCHIVESIZE:           13229360
#ARCH:         x86_64
BuildArch:     x86_64
Name:          dotnet-apphost-pack-9.0
Version:       9.0.3
Release:       1
License:       MIT and ASL 2.0 and BSD 
Group:         default
Summary:       Microsoft.NETCore.App.Host 9.0.3


URL:           https://github.com/dotnet/core
Vendor:        .NET Foundation
Packager:      .NET Team <dotnetpackages@dotnetfoundation.org>





Prefix:        /
Provides:      dotnet-apphost-pack-9.0 = 9.0.3-1
Provides:      dotnet-apphost-pack-9.0(x86-64) = 9.0.3-1
#Requires:      rpmlib(CompressedFileNames) <= 3.0.4-1
#Requires:      rpmlib(FileDigests) <= 4.6.0-1
#Requires:      rpmlib(PayloadFilesHavePrefix) <= 4.0-1





Source: %{rpm_url}
BuildRequires: rpm
%prep
%build
%install
rpm2cpio %{S:0} | cpio --extract --make-directories --preserve-modification-time --verbose --directory %{buildroot}

%description
.NET is a development platform that you can use to build command-line applications, microservices and modern websites. It is open source, cross-platform and is supported by Microsoft. We hope you enjoy using it! If you do, please consider joining the active community of developers that are contributing to the project on GitHub (https://github.com/dotnet/core). We happily accept issues and PRs.
%files
%doc %attr(0764, root, root) "/usr/share/doc/dotnet-apphost-pack-9.0/copyright"
%attr(0755, root, root) "/usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/9.0.3/runtimes/linux-x64/native/apphost"
%attr(0644, root, root) "/usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/9.0.3/runtimes/linux-x64/native/coreclr_delegates.h"
%attr(0644, root, root) "/usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/9.0.3/runtimes/linux-x64/native/hostfxr.h"
%attr(0644, root, root) "/usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/9.0.3/runtimes/linux-x64/native/libnethost.a"
%attr(0755, root, root) "/usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/9.0.3/runtimes/linux-x64/native/libnethost.so"
%attr(0644, root, root) "/usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/9.0.3/runtimes/linux-x64/native/nethost.h"
%attr(0755, root, root) "/usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/9.0.3/runtimes/linux-x64/native/singlefilehost"








%defattr(0644, root, root, 0755)

%dir "/usr/share/doc/%{name}"
%dir "/usr/share/dotnet"
%dir "/usr/share/dotnet/packs"
"/usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64"

%changelog