%define rpm_url https://packages.microsoft.com/opensuse/15/prod/Packages/d/dotnet-runtime-9.0-9.0.3-1.x86_64.rpm
# rpmrebuild autogenerated specfile

%define defaultbuildroot /
AutoProv: no
%undefine __find_provides
AutoReq: no
%undefine __find_requires
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0
#dummy
#dummy
#BUILDHOST:    abd8d6351f20
#BUILDTIME:    Tue Feb 11 23:29:35 2025
#SOURCERPM:    dotnet-runtime-9.0-9.0.3-1.src.rpm

#RPMVERSION:   4.18.2



#OS:           linux
#SIZE:           77530140
#ARCHIVESIZE:           77566916
#ARCH:         x86_64
BuildArch:     x86_64
Name:          dotnet-runtime-9.0
Version:       9.0.3
Release:       1
License:       MIT and ASL 2.0 and BSD 
Group:         default
Summary:       Microsoft.NETCore.App.Runtime 9.0.3


URL:           https://github.com/dotnet/core
Vendor:        .NET Foundation
Packager:      .NET Team <dotnetpackages@dotnetfoundation.org>





Prefix:        /
Provides:      dotnet-runtime-9.0 = 9.0.3-1
Provides:      dotnet-runtime-9.0(x86-64) = 9.0.3-1
Requires:      dotnet-hostfxr-9.0 >= 9.0.3
Requires:      dotnet-runtime-deps-9.0 >= 9.0.3
#Requires:      rpmlib(CompressedFileNames) <= 3.0.4-1
#Requires:      rpmlib(FileDigests) <= 4.6.0-1
#Requires:      rpmlib(PayloadFilesHavePrefix) <= 4.0-1





BuildRequires: dotnet-runtime-deps-9.0

Source: %{rpm_url}
BuildRequires: rpm
%prep
%build
%install
rpm2cpio %{S:0} | cpio --extract --make-directories --preserve-modification-time --verbose --directory %{buildroot}

%description
.NET is a development platform that you can use to build command-line applications, microservices and modern websites. It is open source, cross-platform and is supported by Microsoft. We hope you enjoy using it! If you do, please consider joining the active community of developers that are contributing to the project on GitHub (https://github.com/dotnet/core). We happily accept issues and PRs.
%files
%doc %attr(0764, root, root) "/usr/share/doc/dotnet-runtime-9.0/copyright"
%dir %attr(0755, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App"
%dir %attr(0755, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/.version"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/Microsoft.CSharp.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/Microsoft.NETCore.App.deps.json"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/Microsoft.NETCore.App.runtimeconfig.json"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/Microsoft.VisualBasic.Core.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/Microsoft.VisualBasic.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/Microsoft.Win32.Primitives.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/Microsoft.Win32.Registry.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.AppContext.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Buffers.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Collections.Concurrent.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Collections.Immutable.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Collections.NonGeneric.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Collections.Specialized.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Collections.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.ComponentModel.Annotations.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.ComponentModel.DataAnnotations.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.ComponentModel.EventBasedAsync.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.ComponentModel.Primitives.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.ComponentModel.TypeConverter.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.ComponentModel.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Configuration.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Console.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Core.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Data.Common.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Data.DataSetExtensions.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Data.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Diagnostics.Contracts.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Diagnostics.Debug.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Diagnostics.DiagnosticSource.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Diagnostics.FileVersionInfo.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Diagnostics.Process.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Diagnostics.StackTrace.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Diagnostics.TextWriterTraceListener.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Diagnostics.Tools.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Diagnostics.TraceSource.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Diagnostics.Tracing.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Drawing.Primitives.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Drawing.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Dynamic.Runtime.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Formats.Asn1.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Formats.Tar.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Globalization.Calendars.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Globalization.Extensions.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Globalization.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.IO.Compression.Brotli.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.IO.Compression.FileSystem.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.IO.Compression.ZipFile.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.IO.Compression.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.IO.FileSystem.AccessControl.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.IO.FileSystem.DriveInfo.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.IO.FileSystem.Primitives.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.IO.FileSystem.Watcher.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.IO.FileSystem.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.IO.IsolatedStorage.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.IO.MemoryMappedFiles.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.IO.Pipelines.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.IO.Pipes.AccessControl.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.IO.Pipes.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.IO.UnmanagedMemoryStream.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.IO.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Linq.Expressions.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Linq.Parallel.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Linq.Queryable.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Linq.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Memory.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Net.Http.Json.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Net.Http.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Net.HttpListener.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Net.Mail.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Net.NameResolution.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Net.NetworkInformation.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Net.Ping.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Net.Primitives.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Net.Quic.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Net.Requests.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Net.Security.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Net.ServicePoint.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Net.Sockets.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Net.WebClient.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Net.WebHeaderCollection.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Net.WebProxy.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Net.WebSockets.Client.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Net.WebSockets.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Net.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Numerics.Vectors.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Numerics.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.ObjectModel.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Private.CoreLib.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Private.DataContractSerialization.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Private.Uri.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Private.Xml.Linq.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Private.Xml.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Reflection.DispatchProxy.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Reflection.Emit.ILGeneration.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Reflection.Emit.Lightweight.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Reflection.Emit.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Reflection.Extensions.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Reflection.Metadata.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Reflection.Primitives.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Reflection.TypeExtensions.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Reflection.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Resources.Reader.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Resources.ResourceManager.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Resources.Writer.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Runtime.CompilerServices.Unsafe.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Runtime.CompilerServices.VisualC.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Runtime.Extensions.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Runtime.Handles.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Runtime.InteropServices.JavaScript.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Runtime.InteropServices.RuntimeInformation.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Runtime.InteropServices.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Runtime.Intrinsics.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Runtime.Loader.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Runtime.Numerics.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Runtime.Serialization.Formatters.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Runtime.Serialization.Json.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Runtime.Serialization.Primitives.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Runtime.Serialization.Xml.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Runtime.Serialization.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Runtime.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Security.AccessControl.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Security.Claims.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Security.Cryptography.Algorithms.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Security.Cryptography.Cng.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Security.Cryptography.Csp.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Security.Cryptography.Encoding.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Security.Cryptography.OpenSsl.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Security.Cryptography.Primitives.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Security.Cryptography.X509Certificates.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Security.Cryptography.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Security.Principal.Windows.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Security.Principal.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Security.SecureString.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Security.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.ServiceModel.Web.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.ServiceProcess.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Text.Encoding.CodePages.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Text.Encoding.Extensions.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Text.Encoding.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Text.Encodings.Web.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Text.Json.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Text.RegularExpressions.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Threading.Channels.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Threading.Overlapped.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Threading.Tasks.Dataflow.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Threading.Tasks.Extensions.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Threading.Tasks.Parallel.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Threading.Tasks.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Threading.Thread.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Threading.ThreadPool.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Threading.Timer.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Threading.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Transactions.Local.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Transactions.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.ValueTuple.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Web.HttpUtility.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Web.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Windows.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Xml.Linq.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Xml.ReaderWriter.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Xml.Serialization.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Xml.XDocument.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Xml.XPath.XDocument.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Xml.XPath.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Xml.XmlDocument.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Xml.XmlSerializer.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.Xml.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/System.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/WindowsBase.dll"
%attr(0755, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/createdump"
%attr(0755, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/libSystem.Globalization.Native.so"
%attr(0755, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/libSystem.IO.Compression.Native.so"
%attr(0755, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/libSystem.Native.so"
%attr(0755, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/libSystem.Net.Security.Native.so"
%attr(0755, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/libSystem.Security.Cryptography.Native.OpenSsl.so"
%attr(0755, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/libclrgc.so"
%attr(0755, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/libclrgcexp.so"
%attr(0755, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/libclrjit.so"
%attr(0755, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/libcoreclr.so"
%attr(0755, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/libcoreclrtraceptprovider.so"
%attr(0755, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/libhostpolicy.so"
%attr(0755, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/libmscordaccore.so"
%attr(0755, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/libmscordbi.so"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/mscorlib.dll"
%attr(0644, root, root) "/usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.3/netstandard.dll"








%defattr(0644, root, root, 0755)

%dir "/usr/share/dotnet/shared"
%dir "/usr/share/doc/%{name}"

%changelog