%define rpm_url https://packages.microsoft.com/opensuse/15/prod/Packages/a/aspnetcore-runtime-9.0-9.0.2-1.x86_64.rpm
# rpmrebuild autogenerated specfile

%define defaultbuildroot /
AutoProv: no
%undefine __find_provides
AutoReq: no
%undefine __find_requires
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0
#dummy
#dummy
#BUILDHOST:    a0b4daee9b34
#BUILDTIME:    Fri Jan 17 20:02:10 2025
#SOURCERPM:    aspnetcore-runtime-9.0-9.0.2-1.src.rpm

#RPMVERSION:   4.18.0



#OS:           linux
#SIZE:           24691343
#ARCHIVESIZE:           24721904
#ARCH:         x86_64
BuildArch:     x86_64
Name:          aspnetcore-runtime-9.0
Version:       9.0.2
Release:       1
License:       MIT 
Group:         default
Summary:       Microsoft ASP.NET Core 9.0.2 Shared Framework


URL:           https://asp.net
Vendor:        Microsoft Corporation
Packager:      Microsoft <nugetaspnet@microsoft.com>





Prefix:        /
Provides:      aspnetcore-runtime-9.0 = 9.0.2-1
Provides:      aspnetcore-runtime-9.0(x86-64) = 9.0.2-1
Requires:      dotnet-runtime-9.0 >= 9.0.2
#Requires:      rpmlib(CompressedFileNames) <= 3.0.4-1
#Requires:      rpmlib(FileDigests) <= 4.6.0-1
#Requires:      rpmlib(PayloadFilesHavePrefix) <= 4.0-1





BuildRequires: dotnet-runtime-deps-9.0

Source: %{rpm_url}
BuildRequires: rpm
%prep
%build
%install
rpm2cpio %{S:0} | cpio --extract --make-directories --preserve-modification-time --verbose --directory %{buildroot}

%description
Shared Framework for hosting of Microsoft ASP.NET Core applications. It is open source, cross-platform and is supported by Microsoft. We hope you enjoy using it! If you do, please consider joining the active community of developers that are contributing to the project on GitHub (https://github.com/dotnet/aspnetcore). We happily accept issues and PRs.
%files
%dir %attr(0755, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App"
%dir %attr(0755, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/.version"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Antiforgery.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.App.deps.json"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.App.runtimeconfig.json"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Authentication.Abstractions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Authentication.BearerToken.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Authentication.Cookies.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Authentication.Core.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Authentication.OAuth.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Authentication.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Authorization.Policy.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Authorization.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Components.Authorization.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Components.Endpoints.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Components.Forms.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Components.Server.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Components.Web.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Components.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Connections.Abstractions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.CookiePolicy.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Cors.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Cryptography.Internal.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Cryptography.KeyDerivation.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.DataProtection.Abstractions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.DataProtection.Extensions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.DataProtection.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Diagnostics.Abstractions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Diagnostics.HealthChecks.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Diagnostics.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.HostFiltering.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Hosting.Abstractions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Hosting.Server.Abstractions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Hosting.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Html.Abstractions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Http.Abstractions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Http.Connections.Common.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Http.Connections.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Http.Extensions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Http.Features.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Http.Results.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Http.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.HttpLogging.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.HttpOverrides.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.HttpsPolicy.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Identity.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Localization.Routing.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Localization.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Metadata.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Mvc.Abstractions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Mvc.ApiExplorer.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Mvc.Core.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Mvc.Cors.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Mvc.DataAnnotations.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Mvc.Formatters.Json.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Mvc.Formatters.Xml.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Mvc.Localization.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Mvc.Razor.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Mvc.RazorPages.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Mvc.TagHelpers.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Mvc.ViewFeatures.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Mvc.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.OutputCaching.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.RateLimiting.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Razor.Runtime.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Razor.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.RequestDecompression.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.ResponseCaching.Abstractions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.ResponseCaching.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.ResponseCompression.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Rewrite.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Routing.Abstractions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Routing.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Server.HttpSys.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Server.IIS.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Server.IISIntegration.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Server.Kestrel.Core.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Server.Kestrel.Transport.NamedPipes.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Server.Kestrel.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.Session.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.SignalR.Common.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.SignalR.Core.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.SignalR.Protocols.Json.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.SignalR.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.StaticAssets.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.StaticFiles.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.WebSockets.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.WebUtilities.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.AspNetCore.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Caching.Abstractions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Caching.Memory.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Configuration.Abstractions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Configuration.Binder.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Configuration.CommandLine.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Configuration.EnvironmentVariables.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Configuration.FileExtensions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Configuration.Ini.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Configuration.Json.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Configuration.KeyPerFile.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Configuration.UserSecrets.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Configuration.Xml.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Configuration.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.DependencyInjection.Abstractions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.DependencyInjection.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Diagnostics.Abstractions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Diagnostics.HealthChecks.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Diagnostics.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Features.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.FileProviders.Abstractions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.FileProviders.Composite.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.FileProviders.Embedded.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.FileProviders.Physical.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.FileSystemGlobbing.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Hosting.Abstractions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Hosting.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Http.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Identity.Core.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Identity.Stores.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Localization.Abstractions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Localization.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Logging.Abstractions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Logging.Configuration.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Logging.Console.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Logging.Debug.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Logging.EventLog.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Logging.EventSource.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Logging.TraceSource.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Logging.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.ObjectPool.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Options.ConfigurationExtensions.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Options.DataAnnotations.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Options.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.Primitives.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Extensions.WebEncoders.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.JSInterop.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/Microsoft.Net.Http.Headers.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/System.Diagnostics.EventLog.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/System.Security.Cryptography.Pkcs.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/System.Security.Cryptography.Xml.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/System.Threading.RateLimiting.dll"
%attr(0664, root, root) "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/9.0.2/THIRD-PARTY-NOTICES.txt"








%defattr(0644, root, root, 0755)

%dir "/usr/share/dotnet/shared"

%changelog